favicon: null
name: sleepafter
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9644752976018935
  brandStrength: 0.1219679173082113
  rhythmicContrast: 0.865470013115555
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.883103888714686
typography_spectrum: 0.4444444
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8182488554157317
analytics:
  twitter: null
  google: null
  facebook: null
